---
name: Delete RC testing branch upon PR closure

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify and Delete RC testing branch
        env:
          branch_name: ${{ github.event.pull_request.head.ref }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git fetch --prune --all

          if [[ "$branch_name" == rc-test-* ]]; then
            git push origin --delete $branch_name
          else
            echo "Branch does not have the required RC testing prefix. Skipping branch deletion."
          fi
